import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { searchNowcoderJobs } from './job-discovery/nowcoder.mjs';
import { searchMokaJobs } from './job-discovery/moka.mjs';
import { searchBeisenJobs } from './job-discovery/beisen.mjs';
import { searchFeishuJobs } from './job-discovery/feishu.mjs';
import { searchHotjobJobs } from './job-discovery/hotjob.mjs';
import { searchAnkerJobs } from './job-discovery/anker.mjs';
import { searchEcoflowJobs } from './job-discovery/ecoflow.mjs';
import { relevanceScore, isClosed } from './job-discovery/core.mjs';
import { shouldExcludeByPolicy, jobPolicyReasons, enrichCandidateFit } from './job-discovery/policy.mjs';
import { enrichProvenanceFields } from '../src/core/source-provenance.js';
import { buildSourceHealth } from './job-discovery/source-health.mjs';
import { curateDiscoveredJobs, curatedOfficialGranularityJobs } from './job-discovery/granularity.mjs';
import { retainedJobsForUnhealthySources, providerOfJob, findHistoricalProviderJobs } from './job-discovery/snapshot-retention.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const config = JSON.parse(await fs.readFile(path.join(root, 'config/search-profile.json'), 'utf8'));
const officialSources = JSON.parse(await fs.readFile(path.join(root, 'config/official-sources.json'), 'utf8'));
const livePath = path.join(root, 'src/data/live-jobs.js');
const sourceHealthPath = path.join(root, 'src/data/source-health.js');

// 并发控制：同时最多运行 MAX_CONCURRENCY 个任务
const MAX_CONCURRENCY = 3;

async function runWithConcurrency(tasks, maxConcurrency = MAX_CONCURRENCY) {
  const results = new Array(tasks.length);
  let index = 0;

  async function worker() {
    while (index < tasks.length) {
      const currentIndex = index++;
      const task = tasks[currentIndex];
      try {
        results[currentIndex] = { status: 'fulfilled', value: await task.fn() };
      } catch (error) {
        results[currentIndex] = { status: 'rejected', reason: error };
      }
    }
  }

  const workers = Array.from({ length: Math.min(maxConcurrency, tasks.length) }, () => worker());
  await Promise.all(workers);
  return results;
}

async function loadExisting() {
  try {
    const mod = await import(`${pathToFileURL(livePath).href}?t=${Date.now()}`);
    return Array.isArray(mod.liveJobs) ? mod.liveJobs : [];
  } catch { return []; }
}

function cleanForStorage(job) {
  const { _searchText, _category, _subject, _sourceJobId, _recruitType, closed, excludeFromLiveBoard, ...clean } = job;
  return clean;
}

function asModule(jobs, meta) {
  return `// AUTO-GENERATED by scripts/refresh-jobs.mjs.\nexport const liveJobs = ${JSON.stringify(jobs, null, 2)};\n\nexport const discoveryMeta = ${JSON.stringify(meta, null, 2)};\n`;
}

function healthModule(health, updatedAt) {
  return `// AUTO-GENERATED by scripts/refresh-jobs.mjs.\nexport const sourceHealth = ${JSON.stringify({ ...health, updatedAt }, null, 2)};\n`;
}

function dedupePreferOfficial(jobs = []) {
  const rank = (j) => j?.sourceType === 'official' ? 2 : j?.sourceType === 'secondary' ? 1 : 0;
  const map = new Map();
  for (const job of jobs) {
    if (!job?.id) continue;
    const key = `${String(job.company || '').trim().toLowerCase()}|${String(job.title || '').replace(/[\s【】〖〗()（）\-_]/g,'').toLowerCase()}|${String(job.city || '').trim().toLowerCase()}`;
    const prev = map.get(key);
    if (!prev || rank(job) > rank(prev) || (rank(job) === rank(prev) && String(job.publishedAt || '') > String(prev.publishedAt || ''))) map.set(key, job);
  }
  return [...map.values()];
}

function countPolicyReasons(jobs = []) {
  const stats = {};
  for (const job of jobs) {
    for (const reason of jobPolicyReasons(job)) stats[reason] = (stats[reason] || 0) + 1;
  }
  return stats;
}

function sourceConfigured(provider) {
  if (provider === 'nowcoder') return true;
  const value = officialSources?.[provider];
  return Array.isArray(value) ? value.length > 0 : Boolean(value);
}

function logSourceResult(name, result) {
  const stats = result?.stats || {};
  const parts = [];
  if (stats.portals !== undefined) parts.push(`portals=${stats.scannedPortals}/${stats.portals}`);
  if (stats.discoveredUrls !== undefined) parts.push(`discovered=${stats.discoveredUrls}`);
  if (stats.scannedPages !== undefined) parts.push(`scanned=${stats.scannedPages}`);
  if (stats.scannedRows !== undefined) parts.push(`rows=${stats.scannedRows}`);
  if (stats.listed !== undefined) parts.push(`listed=${stats.listed}`);
  if (stats.detailed !== undefined) parts.push(`detailed=${stats.detailed}`);
  if (stats.pages !== undefined) parts.push(`pages=${stats.pages}`);
  parts.push(`kept=${stats.keptJobs}`);
  parts.push(`errors=${stats.errors}`);
  if (stats.snapshotComplete !== undefined) parts.push(`complete=${stats.snapshotComplete}`);
  console.log(`[job-refresh:${name}] ${parts.join(' ')}`);
}

const existing = await loadExisting();
const sourceResults = [];
let chromium = null;
try { chromium = (await import('playwright')).chromium; } catch {}

console.log(`[job-refresh] starting refresh with concurrency=${MAX_CONCURRENCY}`);

// === 第一阶段：moka 单独运行（需要 Playwright，资源占用大）===
try {
  if (!chromium) throw new Error('Playwright Chromium unavailable');
  console.log('[job-refresh:moka] starting (Playwright, isolated)');
  const moka = await searchMokaJobs(config, officialSources.moka || [], { chromium });
  sourceResults.push({ name: 'moka', ...moka });
  logSourceResult('moka', moka);
} catch (error) {
  console.warn(`[job-refresh:moka] skipped: ${error.message}`);
}

// === 第二阶段：其他 6 个源并行运行（纯 HTTP 请求，无需 Playwright）===
const parallelTasks = [];

if (sourceConfigured('nowcoder')) {
  parallelTasks.push({
    name: 'nowcoder',
    fn: async () => {
      console.log('[job-refresh:nowcoder] starting');
      const result = await searchNowcoderJobs(config);
      logSourceResult('nowcoder', result);
      return result;
    }
  });
}

if (sourceConfigured('beisen')) {
  parallelTasks.push({
    name: 'beisen',
    fn: async () => {
      console.log('[job-refresh:beisen] starting');
      const result = await searchBeisenJobs(config, officialSources.beisen || []);
      logSourceResult('beisen', result);
      return result;
    }
  });
}

if (sourceConfigured('feishu')) {
  parallelTasks.push({
    name: 'feishu',
    fn: async () => {
      console.log('[job-refresh:feishu] starting');
      const result = await searchFeishuJobs(config, officialSources.feishu || []);
      logSourceResult('feishu', result);
      return result;
    }
  });
}

if (sourceConfigured('hotjob')) {
  parallelTasks.push({
    name: 'hotjob',
    fn: async () => {
      console.log('[job-refresh:hotjob] starting');
      const result = await searchHotjobJobs(config, officialSources.hotjob || []);
      logSourceResult('hotjob', result);
      return result;
    }
  });
}

if (sourceConfigured('anker') && officialSources.anker) {
  parallelTasks.push({
    name: 'anker',
    fn: async () => {
      console.log('[job-refresh:anker] starting');
      const result = await searchAnkerJobs(config, officialSources.anker, {
        maxJobs: officialSources.anker?.maxJobs,
        pageSize: officialSources.anker?.pageSize,
        maxPages: officialSources.anker?.maxPages
      });
      logSourceResult('anker', result);
      return result;
    }
  });
}

if (sourceConfigured('ecoflow') && officialSources.ecoflow) {
  parallelTasks.push({
    name: 'ecoflow',
    fn: async () => {
      console.log('[job-refresh:ecoflow] starting');
      const result = await searchEcoflowJobs(config, officialSources.ecoflow, {
        maxJobs: officialSources.ecoflow?.maxJobs,
        pageSize: officialSources.ecoflow?.pageSize,
        maxPages: officialSources.ecoflow?.maxPages
      });
      logSourceResult('ecoflow', result);
      return result;
    }
  });
}

console.log(`[job-refresh] running ${parallelTasks.length} sources in parallel (concurrency=${MAX_CONCURRENCY})`);

const parallelResults = await runWithConcurrency(parallelTasks, MAX_CONCURRENCY);

for (let i = 0; i < parallelTasks.length; i++) {
  const task = parallelTasks[i];
  const result = parallelResults[i];
  if (result.status === 'fulfilled') {
    sourceResults.push({ name: task.name, ...result.value });
  } else {
    console.warn(`[job-refresh:${task.name}] failed: ${result.reason.message}`);
  }
}

console.log(`[job-refresh] all sources completed: ${sourceResults.length}/${parallelTasks.length + 1} successful`);

// === 后续处理逻辑保持不变 ===
const configuredProviders = ['nowcoder','moka','beisen','feishu','hotjob','anker','ecoflow'].filter(sourceConfigured);
const snapshotRetention = retainedJobsForUnhealthySources(existing, sourceResults, configuredProviders);
let retainedSourceJobs = [...snapshotRetention.retained];
for (const provider of snapshotRetention.unhealthy) {
  if (retainedSourceJobs.some((job) => providerOfJob(job) === provider)) continue;
  const historical = await findHistoricalProviderJobs({ root, provider });
  if (historical.jobs.length) {
    retainedSourceJobs.push(...historical.jobs);
    console.warn(`[job-refresh:${provider}] unhealthy snapshot; recovered ${historical.jobs.length} jobs from ${historical.commit.slice(0, 8)}`);
  }
}
if (snapshotRetention.unhealthy.length) {
  console.warn(`[job-refresh] unhealthySources=${snapshotRetention.unhealthy.join(',')} retainedSourceJobs=${retainedSourceJobs.length}`);
}

const discoveredJobs = curateDiscoveredJobs(sourceResults.flatMap((r) => r.jobs || []));
const verifiedConcreteJobs = curatedOfficialGranularityJobs();
const candidateJobs = [...discoveredJobs, ...verifiedConcreteJobs];
const granularityExcluded = candidateJobs.filter((job) => job.excludeFromLiveBoard).length;
const policyStats = countPolicyReasons(candidateJobs.filter((job) => !job.excludeFromLiveBoard));

const liveBoardCandidates = candidateJobs
  .filter((job) => !job.excludeFromLiveBoard)
  .filter((job) => !shouldExcludeByPolicy(job))
  .map((job) => enrichCandidateFit(job, config))
  .map((job) => enrichProvenanceFields(job));

const deduped = dedupePreferOfficial([...liveBoardCandidates, ...retainedSourceJobs]);
const finalJobs = deduped
  .filter((job) => !isClosed('', job.deadline))
  .sort((a, b) => String(b.publishedAt || '').localeCompare(String(a.publishedAt || '')) || String(b.company || '').localeCompare(String(a.company || '')));

const sourceHealth = buildSourceHealth(sourceResults, configuredProviders);

const meta = {
  updatedAt: new Date().toISOString(),
  totalJobs: finalJobs.length,
  totalCompanies: new Set(finalJobs.map((j) => j.company)).size,
  sources: sourceResults.map((r) => ({ name: r.name, kept: (r.jobs || []).length, errors: r.stats?.errors || 0 })),
  policyStats,
  granularityExcluded,
  unhealthySources: snapshotRetention.unhealthy,
  retainedJobs: retainedSourceJobs.length
};

await fs.writeFile(livePath, asModule(finalJobs.map(cleanForStorage), meta), 'utf8');
await fs.writeFile(sourceHealthPath, healthModule(sourceHealth, meta.updatedAt), 'utf8');

console.log(`[job-refresh] DONE jobs=${finalJobs.length} companies=${meta.totalCompanies} sources=${sourceResults.length}`);
console.log(`[job-refresh] written to ${path.relative(root, livePath)} and ${path.relative(root, sourceHealthPath)}`);
