import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { searchNowcoderJobs } from './job-discovery/nowcoder.mjs';
import { searchMokaJobs } from './job-discovery/moka.mjs';
import { searchBeisenJobs } from './job-discovery/beisen.mjs';
import { searchFeishuJobs } from './job-discovery/feishu.mjs';
import { searchHotjobJobs } from './job-discovery/hotjob.mjs';
import { searchAnkerJobs } from './job-discovery/anker.mjs';
import { searchEcoflowJobs } from './job-discovery/ecoflow.mjs';
import { relevanceScore, isClosed } from './job-discovery/core.mjs';
import { shouldExcludeByPolicy, jobPolicyReasons, enrichCandidateFit } from './job-discovery/policy.mjs';
import { enrichProvenanceFields } from '../src/core/source-provenance.js';
import { buildSourceHealth } from './job-discovery/source-health.mjs';
import { curateDiscoveredJobs, curatedOfficialGranularityJobs } from './job-discovery/granularity.mjs';
import { retainedJobsForUnhealthySources, providerOfJob, findHistoricalProviderJobs } from './job-discovery/snapshot-retention.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const config = JSON.parse(await fs.readFile(path.join(root, 'config/search-profile.json'), 'utf8'));
const officialSources = JSON.parse(await fs.readFile(path.join(root, 'config/official-sources.json'), 'utf8'));
const livePath = path.join(root, 'src/data/live-jobs.js');
const sourceHealthPath = path.join(root, 'src/data/source-health.js');

async function loadExisting() {
  try {
    const mod = await import(`${pathToFileURL(livePath).href}?t=${Date.now()}`);
    return Array.isArray(mod.liveJobs) ? mod.liveJobs : [];
  } catch { return []; }
}

function cleanForStorage(job) {
  const { _searchText, _category, _subject, _sourceJobId, _recruitType, closed, excludeFromLiveBoard, ...clean } = job;
  return clean;
}

function asModule(jobs, meta) {
  return `// AUTO-GENERATED by scripts/refresh-jobs.mjs.\nexport const liveJobs = ${JSON.stringify(jobs, null, 2)};\n\nexport const discoveryMeta = ${JSON.stringify(meta, null, 2)};\n`;
}

function healthModule(health, updatedAt) {
  return `// AUTO-GENERATED by scripts/refresh-jobs.mjs.\nexport const sourceHealth = ${JSON.stringify({ ...health, updatedAt }, null, 2)};\n`;
}

function dedupePreferOfficial(jobs = []) {
  const rank = (j) => j?.sourceType === 'official' ? 2 : j?.sourceType === 'secondary' ? 1 : 0;
  const map = new Map();
  for (const job of jobs) {
    if (!job?.id) continue;
    const key = `${String(job.company || '').trim().toLowerCase()}|${String(job.title || '').replace(/[\s【】〖〗()（）\-_]/g,'').toLowerCase()}|${String(job.city || '').trim().toLowerCase()}`;
    const prev = map.get(key);
    if (!prev || rank(job) > rank(prev) || (rank(job) === rank(prev) && String(job.publishedAt || '') > String(prev.publishedAt || ''))) map.set(key, job);
  }
  return [...map.values()];
}

function countPolicyReasons(jobs = []) {
  const stats = {};
  for (const job of jobs) {
    for (const reason of jobPolicyReasons(job)) stats[reason] = (stats[reason] || 0) + 1;
  }
  return stats;
}

function sourceConfigured(provider) {
  if (provider === 'nowcoder') return true;
  const value = officialSources?.[provider];
  return Array.isArray(value) ? value.length > 0 : Boolean(value);
}

const existing = await loadExisting();
const sourceResults = [];
let chromium = null;
try { chromium = (await import('playwright')).chromium; } catch {}

try {
  const nowcoder = await searchNowcoderJobs(config);
  sourceResults.push({ name: 'nowcoder', ...nowcoder });
  console.log(`[job-refresh:nowcoder] discovered=${nowcoder.stats.discoveredUrls} scanned=${nowcoder.stats.scannedPages} kept=${nowcoder.stats.keptJobs} errors=${nowcoder.stats.errors}`);
} catch (error) {
  console.warn(`[job-refresh:nowcoder] unavailable: ${error.message}`);
}

try {
  if (!chromium) throw new Error('Playwright Chromium unavailable');
  const moka = await searchMokaJobs(config, officialSources.moka || [], { chromium });
  sourceResults.push({ name: 'moka', ...moka });
  console.log(`[job-refresh:moka] portals=${moka.stats.scannedPortals}/${moka.stats.portals} discovered=${moka.stats.discoveredUrls} kept=${moka.stats.keptJobs} errors=${moka.stats.errors}`);
} catch (error) {
  console.warn(`[job-refresh:moka] skipped: ${error.message}`);
}

try {
  const beisen = await searchBeisenJobs(config, officialSources.beisen || []);
  sourceResults.push({ name: 'beisen', ...beisen });
  console.log(`[job-refresh:beisen] portals=${beisen.stats.scannedPortals}/${beisen.stats.portals} rows=${beisen.stats.scannedRows} kept=${beisen.stats.keptJobs} errors=${beisen.stats.errors}`);
} catch (error) {
  console.warn(`[job-refresh:beisen] skipped: ${error.message}`);
}

try {
  const feishu = await searchFeishuJobs(config, officialSources.feishu || []);
  sourceResults.push({ name: 'feishu', ...feishu });
  console.log(`[job-refresh:feishu] portals=${feishu.stats.scannedPortals}/${feishu.stats.portals} listed=${feishu.stats.listed} kept=${feishu.stats.keptJobs} errors=${feishu.stats.errors}`);
} catch (error) {
  console.warn(`[job-refresh:feishu] skipped: ${error.message}`);
}

try {
  const hotjob = await searchHotjobJobs(config, officialSources.hotjob || []);
  sourceResults.push({ name: 'hotjob', ...hotjob });
  console.log(`[job-refresh:hotjob] portals=${hotjob.stats.scannedPortals}/${hotjob.stats.portals} listed=${hotjob.stats.listed} detailed=${hotjob.stats.detailed} kept=${hotjob.stats.keptJobs} errors=${hotjob.stats.errors}`);
} catch (error) {
  console.warn(`[job-refresh:hotjob] skipped: ${error.message}`);
}

try {
  const anker = await searchAnkerJobs(config, officialSources.anker, {
    maxJobs: officialSources.anker?.maxJobs,
    pageSize: officialSources.anker?.pageSize,
    maxPages: officialSources.anker?.maxPages
  });
  sourceResults.push({ name: 'anker', ...anker });
  console.log(`[job-refresh:anker] pages=${anker.stats.pages} listed=${anker.stats.listed} detailed=${anker.stats.detailed} kept=${anker.stats.keptJobs} errors=${anker.stats.errors} complete=${anker.stats.snapshotComplete}`);
} catch (error) {
  console.warn(`[job-refresh:anker] skipped: ${error.message}`);
}

try {
  const ecoflow = await searchEcoflowJobs(config, officialSources.ecoflow, {
    maxJobs: officialSources.ecoflow?.maxJobs,
    pageSize: officialSources.ecoflow?.pageSize,
    maxPages: officialSources.ecoflow?.maxPages
  });
  sourceResults.push({ name: 'ecoflow', ...ecoflow });
  console.log(`[job-refresh:ecoflow] pages=${ecoflow.stats.pages} listed=${ecoflow.stats.listed} kept=${ecoflow.stats.keptJobs} errors=${ecoflow.stats.errors} complete=${ecoflow.stats.snapshotComplete}`);
} catch (error) {
  console.warn(`[job-refresh:ecoflow] skipped: ${error.message}`);
}

const configuredProviders = ['nowcoder','moka','beisen','feishu','hotjob','anker','ecoflow'].filter(sourceConfigured);
const snapshotRetention = retainedJobsForUnhealthySources(existing, sourceResults, configuredProviders);
let retainedSourceJobs = [...snapshotRetention.retained];
for (const provider of snapshotRetention.unhealthy) {
  if (retainedSourceJobs.some((job) => providerOfJob(job) === provider)) continue;
  const historical = await findHistoricalProviderJobs({ root, provider });
  if (historical.jobs.length) {
    retainedSourceJobs.push(...historical.jobs);
    console.warn(`[job-refresh:${provider}] unhealthy snapshot; recovered ${historical.jobs.length} jobs from ${historical.commit.slice(0, 8)}`);
  }
}
if (snapshotRetention.unhealthy.length) {
  console.warn(`[job-refresh] unhealthySources=${snapshotRetention.unhealthy.join(',')} retainedSourceJobs=${retainedSourceJobs.length}`);
}

const discoveredJobs = curateDiscoveredJobs(sourceResults.flatMap((r) => r.jobs || []));
const verifiedConcreteJobs = curatedOfficialGranularityJobs();
const candidateJobs = [...discoveredJobs, ...verifiedConcreteJobs];
const granularityExcluded = candidateJobs.filter((job) => job.excludeFromLiveBoard).length;
const policyStats = countPolicyReasons(candidateJobs.filter((job) => !job.excludeFromLiveBoard));
const freshJobs = candidateJobs
  .filter((job) => !job.excludeFromLiveBoard)
  .filter((job) => !shouldExcludeByPolicy(job))
  .map(enrichCandidateFit);
if (!freshJobs.length && !retainedSourceJobs.length) {
  console.warn('[job-refresh] no fresh matching jobs found; keeping existing live job pool unchanged.');
  process.exit(0);
}

const now = new Date();
const retainedHealthySnapshot = retainedSourceJobs
  .filter((job) => !isClosed('', job.deadline, now) && !shouldExcludeByPolicy(job))
  .map(enrichCandidateFit);
const retainedSeeds = existing
  .filter((job) => !job.discoveredAt && !shouldExcludeByPolicy(job))
  .map(enrichCandidateFit);
const merged = dedupePreferOfficial([...freshJobs, ...retainedHealthySnapshot, ...retainedSeeds])
  .filter((job) => !isClosed('', job.deadline, now) && !shouldExcludeByPolicy(job))
  .sort((a,b) => {
    const scoreDiff = relevanceScore(b, config) - relevanceScore(a, config);
    if (scoreDiff) return scoreDiff;
    if (a.sourceType !== b.sourceType) return a.sourceType === 'official' ? -1 : b.sourceType === 'official' ? 1 : 0;
    return String(b.publishedAt || '').localeCompare(String(a.publishedAt || ''));
  })
  .slice(0, Number(config.maxJobs || 300))
  .map(cleanForStorage);

const companies = new Set(merged.map((job) => job.company).filter(Boolean));
const finalJobs = merged.map(enrichProvenanceFields);
const sourceStats = Object.fromEntries(sourceResults.map((r) => [r.name, r.stats]));
const sourceHealth = buildSourceHealth(sourceStats, officialSources);
const updatedAt = new Date().toISOString();
const meta = {
  updatedAt,
  source: '多源：公司官方招聘官网/API + 牛客公开职位 + 官网核验具体岗位',
  mode: '官方多ATS源优先去重 + 来源失败快照保留 + 官网粒度校正 + JD专业/技术/小语种硬门槛过滤 + 英语专业适配信号',
  stats: { sources: sourceStats, sourceHealth, unhealthySources: snapshotRetention.unhealthy, retainedSourceJobs: retainedHealthySnapshot.length, verifiedConcreteJobs: verifiedConcreteJobs.length, granularityExcluded, policyExcluded: policyStats, retainedSeeds: retainedSeeds.length, totalJobs: merged.length, companies: companies.size },
  note: '岗位名、届别/专业要求与岗位方向分层处理。来源本轮抓取报错、返回不完整快照或异常空结果时，不用该结果清空历史岗位；先保留该来源最近一次有效岗位快照，待来源恢复后再替换。已官网核验的具体岗位作为确定性记录进入岗位池，不依赖二手源每次都能重新抓到。硬淘汰：纯销售、实习、明确技术工程/实施岗位、明确必须理工科/技术专业、硬技术能力、必须专业资格证书、必须小语种。小语种仅为优先/加分项，或英语与小语种明确任选其一时保留。'
};

await fs.writeFile(livePath, asModule(finalJobs, meta), 'utf8');
await fs.writeFile(sourceHealthPath, healthModule(sourceHealth, updatedAt), 'utf8');
console.log(`[job-refresh] sourceHealth=${sourceHealth.healthy}/${sourceHealth.total} healthy; attention=${sourceHealth.attention}`);
console.log(`[job-refresh] verifiedConcreteJobs=${verifiedConcreteJobs.length} granularityExcluded=${granularityExcluded} policyExcluded=${JSON.stringify(policyStats)}`);
console.log(`[job-refresh] wrote ${finalJobs.length} jobs across ${companies.size} companies; retainedSeeds=${retainedSeeds.length} retainedSourceJobs=${retainedHealthySnapshot.length}.`);
